version: '3.9'

services:
  php:
    container_name: php
    hostname: yii2.local
    networks:
      - default
      - yii2
    depends_on:
      mysql:
        condition: service_started
    build:
      context: docker/php
    ports:
      - '80:80'
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    env_file:
      - docker/.env
  mysql:
    container_name: yii2-mysql
    hostname: yii2-mysql
    image: mysql:5.7
#    ports:
#      - '3307:3306'
    volumes:
      - ./docker/dbdata:/var/lib/mysql
      - ./docker/dblog:/var/log/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yii2
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
    networks:
      - default
networks:
  yii2:
    name: yii2
#    external: true
